// <auto-generated />
using System;
using Data_Access_Layer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TestCase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data_Access_Layer.Common.Models.CarDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateRelease");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTimeOffset?>("TimeAdd");

                    b.Property<DateTimeOffset?>("TimeModified");

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Data_Access_Layer.Common.Models.OrderDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CarId");

                    b.Property<string>("Information")
                        .HasMaxLength(255);

                    b.Property<DateTimeOffset?>("TimeAdd");

                    b.Property<DateTimeOffset?>("TimeEnd")
                        .IsRequired();

                    b.Property<DateTimeOffset?>("TimeModified");

                    b.Property<DateTimeOffset?>("TimeStart")
                        .IsRequired();

                    b.Property<Guid>("UsertId");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UsertId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Data_Access_Layer.Common.Models.UserDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NumberDL")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTimeOffset?>("TimeAdd");

                    b.Property<DateTimeOffset?>("TimeModified");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Data_Access_Layer.Common.Models.OrderDB", b =>
                {
                    b.HasOne("Data_Access_Layer.Common.Models.CarDB", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Data_Access_Layer.Common.Models.UserDB", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UsertId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
